id: medcom.fhir.dk.messaging
canonical: http://medcomfhir.dk/ig/messaging
name: MedComMessaging
title: "DK MedCom Messaging"
description: This IG includes messaging profiles defined by MedCom. These profiles are used in messagebased communication.
status: active
version: 2.2.2
fhirVersion: 4.0.1
copyrightYear: 2021+
releaseLabel: release
publisher:
  name: MedCom
  url: http://www.medcom.dk
jurisdiction: urn:iso:std:iso:3166#DK "Denmark"
dependencies:
  hl7.fhir.dk.core: 3.2.0
  medcom.fhir.dk.core: 2.4.0
  
menu:
  Table of Contents: toc.html
  Home: index.html
  Profiles: profiles.html
  Extensions: extensions.html
  Artifacts: artifacts.html
  Downloads: downloads.html

parameters:
  apply-contact: true
  apply-jurisdiction: true
  apply-publisher: true
