id: medcom.fhir.dk.messaging
canonical: http://medcomfhir.dk/ig/messaging
name: DK MedCom Messaging
title: DK MedCom Messaging
description: This IG includes messaging profiles defined by MedCom. These profiles are used in messagebased communication
status: active
version: 3.0.0
fhirVersion: 4.0.1
copyrightYear: 2021+
releaseLabel: release
publisher:
  name: MedCom
  url: http://www.medcom.dk
jurisdiction: urn:iso:std:iso:3166#DK "Denmark"
dependencies:
  hl7.fhir.dk.core: 3.4.0
  medcom.fhir.dk.core: 3.0.0
  
menu:
  Table of Contents: toc.html
  Home: index.html
  Profiles: profiles.html
  Extensions: extensions.html
  Artifacts: artifacts.html
  Dependencies: dependencies.html
  Downloads: downloads.html


parameters:
  apply-contact: true
  apply-jurisdiction: true
  apply-publisher: true
