@startuml MedComMessageHeader

hide empty members

class "MedComMessagingMessageHeader" as messageHeader
class "MedComMessagingOrganization" as organization <<MedComCoreOrganization>>


messageHeader -- organization : "sender"
messageHeader -- organization : "receiver"
messageHeader -- organization : "carbon-copy"

@enduml