@startuml MessagingModel

hide empty members

class "MedComMessagingMessage" as message
class "MedComMessagingMessageHeader" as messageHeader
class "MedComMessagingOrganization" as organization <<MedComCoreOrganization>>
class "MedComMessagingProvenance" as provenance

message -- messageHeader : "entry"
message -- provenance : "entry"

provenance -- organization : "agent.who"

messageHeader -- organization : "sender"
messageHeader -- organization : "receiver"
messageHeader -- organization : "carbon-copy"

@enduml